### PR TITLE
Rpl msg source empty

### PR DESCRIPTION
**Pull request by Bee-Have**
⚠️  WARNING ⚠️ 
THIS PULL REQUEST MUST BE TREATED AFTER #47 (it changes Part files)

The problem was comming from the message class.
format_reply() was using Message.emitter_name to fill the <client> part of the message.
However this variable was not always set in the code and my calls of it in JOIN and PART.

The constructor : Message(int emitter)
has therefore been replaced by : Message(int p_emitter, std::string p_name)

this avoids any further possible errors that might occur.
Usually this is not an issue as the originated message (created in receive_message.cpp) uses the constructor "Message(const Client &emitter)" which sets emitter_name correctly.

### CODE REVIEW

**Comment by jfremond** [comment]
I still have this issue when I test the program. I'm attaching an image below

Screenshot from 2023-09-08 15-22-06

**Comment by Bee-Have** [comment]
could you tell me the other lines here, i tried to reproduce the test but i got the right behavior
Screenshot 2023-09-09 134600

**Comment by jfremond** [comment]
These are all the commands I tested, I made sure I was on the right branch and that it was updated but I still have the same issue
image

**Comment by Bee-Have** [comment]
i tried those exact commands, i don't have the same result. Are you sure you built te executable after switching branch ?
Screenshot 2023-09-09 142735

**Comment by jfremond** [comment]
I did build the executable after switching branch. I did a `make fclean` followed by a `make` to be sure but i still have the same issue
image

**Comment by Bee-Have** [comment]
it would appear the actual fix which i thought was pushed was not, I'm fixing it now

**Pull request merged**
